# Generated by Django 6.0 on 2025-12-29 15:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, null=True, verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_ar', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('role', models.CharField(choices=[('super_admin', 'مدير رئيسي'), ('admin', 'مدير'), ('moderator', 'مشرف')], default='admin', max_length=50, verbose_name='الدور')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مسؤول',
                'verbose_name_plural': 'المسؤولين',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image_url', models.CharField(max_length=500, verbose_name='رابط الصورة')),
                ('button_text_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الزر')),
                ('button_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الزر')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['is_active'], name='store_banne_is_acti_172c50_idx'), models.Index(fields=['display_order'], name='store_banne_display_903d81_idx')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم بالإنجليزية')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'براند',
                'verbose_name_plural': 'البراندات',
                'ordering': ['name_ar'],
                'indexes': [models.Index(fields=['is_active'], name='store_brand_is_acti_a8ec4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='الرابط الودي')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف بالعربية')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الصورة')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='store.category', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_amount', 'قيمة ثابتة')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للخصم')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='حد الاستخدام')),
                ('usage_count', models.IntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': 'أكواد الخصم',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='store_disco_code_bade6a_idx'), models.Index(fields=['is_active'], name='store_disco_is_acti_2d2217_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('district', models.CharField(max_length=100, verbose_name='المركز')),
                ('village', models.CharField(blank=True, max_length=100, null=True, verbose_name='القرية')),
                ('detailed_address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المجموع الفرعي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الخصم')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الشحن')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('out_for_delivery', 'قيد التوصيل'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=50, verbose_name='حالة الطلب')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات العميل')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='store_order_order_n_317f52_idx'), models.Index(fields=['customer_phone'], name='store_order_custome_5fda04_idx'), models.Index(fields=['status'], name='store_order_status_428b25_idx'), models.Index(fields=['-created_at'], name='store_order_created_cad692_idx'), models.Index(fields=['governorate'], name='store_order_governo_b06158_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='الحالة القديمة')),
                ('new_status', models.CharField(max_length=50, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حالة طلب',
                'verbose_name_plural': 'سجلات حالة الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='كود المنتج')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='الرابط الودي')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='الوصف بالإنجليزية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المتاحة')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='متوفر')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='حد التنبيه للمخزون')),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='مثال: S, M, L, XL, XXL', null=True, verbose_name='المقاسات المتاحة')),
                ('available_colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='مثال: أبيض, أسود, أزرق', null=True, verbose_name='الألوان المتاحة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='عليه تخفيض')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='متوسط التقييم')),
                ('review_count', models.IntegerField(default=0, verbose_name='عدد التقييمات')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('sales_count', models.IntegerField(default=0, verbose_name='عدد المبيعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='البراند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_ar', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='كود المنتج')),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='المقاس المختار')),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون المختار')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='نسبة الخصم')),
                ('final_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة النهائي')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الفرعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج الطلب',
                'verbose_name_plural': 'منتجات الطلبات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500, verbose_name='رابط الصورة')),
                ('alt_text_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='النص البديل')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255, verbose_name='اسم المراجع')),
                ('reviewer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المراجعة')),
                ('comment_ar', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='شراء موثق')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='عدد المفيدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('governorate', models.CharField(max_length=100, unique=True, verbose_name='المحافظة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الشحن')),
                ('estimated_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة التوصيل المتوقعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'منطقة شحن',
                'verbose_name_plural': 'مناطق الشحن',
                'ordering': ['governorate'],
                'indexes': [models.Index(fields=['governorate'], name='store_shipp_governo_e26c95_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['username'], name='store_admin_usernam_bbb786_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['email'], name='store_admin_email_7fb6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['is_active'], name='store_admin_is_acti_f006bf_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='store_categ_slug_3348ec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='store_categ_is_acti_0b4d39_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='store_categ_parent__e56892_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='store_order_order_i_146f10_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['-created_at'], name='store_order_created_7e8f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='store_produ_categor_6683b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='store_produ_brand_i_7fca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='store_produ_is_acti_d3da42_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_a0ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_on_sale'], name='store_produ_is_on_s_792506_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['average_rating'], name='store_produ_average_66cb30_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='store_order_product_056298_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='store_produ_product_f5a1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='store_produ_product_e3fa15_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='store_revie_product_7f7a24_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='store_revie_is_appr_2e0ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='store_revie_rating_af4d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='store_revie_created_805ccb_idx'),
        ),
    ]
