# Generated by Django 6.0 on 2026-01-02 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(verbose_name='صالح حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'كوبونات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='store_coupo_code_db22f9_idx'), models.Index(fields=['product', 'is_active'], name='store_coupo_product_abd2dc_idx')],
            },
        ),
    ]
