# Generated by Django 6.0 on 2026-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='رقم أقل = يظهر أولاً', verbose_name='ترتيب العرض'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['display_order'], name='store_produ_display_a4fa2b_idx'),
        ),
    ]
