# Generated by Django 6.0 on 2026-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_set_initial_display_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coupon',
            name='store_coupo_product_abd2dc_idx',
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='اتركه فارغاً ليعمل على جميع المنتجات', related_name='coupons', to='store.product', verbose_name='المنتجات'),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
