# Generated by Django 6.0 on 2026-02-08 13:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_coupon_store_coupo_product_abd2dc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'الدفع عند الاستلام'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'انستاباي')], default='cash_on_delivery', max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='صورة تأكيد الدفع'),
        ),
        migrations.CreateModel(
            name='PaymentNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('vodafone_cash', 'فودافون كاش'), ('instapay', 'انستاباي')], max_length=50, verbose_name='نوع الدفع')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رقم دفع',
                'verbose_name_plural': 'أرقام الدفع',
                'ordering': ['payment_type', 'display_order'],
                'indexes': [models.Index(fields=['payment_type', 'is_active'], name='store_payme_payment_abc129_idx')],
            },
        ),
    ]
