# Generated by Django 6.0 on 2026-03-03 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_increase_order_totals_max_digits_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق البريد')),
                ('email_verification_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='رمز تفعيل البريد')),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال تفعيل البريد')),
                ('password_reset_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='رمز إعادة تعيين كلمة المرور')),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إرسال إعادة التعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'indexes': [models.Index(fields=['email'], name='store_custo_email_8208ee_idx'), models.Index(fields=['is_active'], name='store_custo_is_acti_20a089_idx'), models.Index(fields=['is_verified'], name='store_custo_is_veri_0c210a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='store.customer')),
            ],
            options={
                'verbose_name': 'رمز جلسة عميل',
                'verbose_name_plural': 'رموز جلسات العملاء',
            },
        ),
    ]
